"""
coruscant.core.erd_generator
~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Renders a Mermaid entity-relationship diagram as a self-contained HTML page.

The Schema Browser queries the catalog and builds the Mermaid ``erDiagram``
source; this module turns that source into the page the browser opens. It needs
no network: Mermaid and svg-pan-zoom are inlined from the copies bundled with
Coruscant (see coruscant.core.vendor), so the diagram renders offline and keeps
working after the file is moved or Coruscant has exited.

Kept apart from the panel, and free of Qt and of any database access, so the
page can be built and checked without either.

No GUI imports.
"""

from __future__ import annotations

from coruscant.core.vendor import inline_script


def render_erd_html(schema: str, mermaid: str, n_tables: int, n_rels: int) -> str:
    """Return the ERD page for *schema*, given its Mermaid ``erDiagram`` source."""
    return (
        "<!DOCTYPE html>\n"
        "<html lang=\"en\">\n"
        "<head>\n"
        "<meta charset=\"utf-8\">\n"
        f"<title>ERD — {schema}</title>\n"
        f"{inline_script('mermaid')}\n"
        f"{inline_script('svg-pan-zoom')}\n"
        "<style>\n"
        "  * { box-sizing:border-box; margin:0; padding:0; }\n"
        "  body { background:#0d0d1a; color:#cdd6f4; font-family:system-ui,sans-serif;\n"
        "          padding:20px; height:100vh; display:flex; flex-direction:column; gap:10px; }\n"
        "  h2  { color:#89b4fa; font-size:17px; flex-shrink:0; }\n"
        "  .meta { color:#666; font-size:11px; flex-shrink:0; }\n"
        "  .toolbar { display:flex; gap:6px; flex-shrink:0; }\n"
        "  .toolbar button {\n"
        "    background:#1e1e2e; color:#cdd6f4; border:1px solid #313244;\n"
        "    border-radius:4px; padding:4px 14px; cursor:pointer; font-size:12px;\n"
        "  }\n"
        "  .toolbar button:hover { background:#313244; border-color:#89b4fa; }\n"
        "  #erd-wrap {\n"
        "    flex:1; background:#1a1a2e; border-radius:8px; border:1px solid #313244;\n"
        "    overflow:hidden; position:relative; min-height:0;\n"
        "  }\n"
        "  #erd-wrap svg { width:100%; height:100%; display:block; }\n"
        "  details { flex-shrink:0; }\n"
        "  summary { cursor:pointer; color:#89b4fa; font-size:12px; padding:4px 0; }\n"
        "  pre { background:#1e1e2e; color:#cdd6f4; padding:14px; border-radius:6px;\n"
        "         font-size:11px; overflow:auto; border:1px solid #313244; margin-top:6px;\n"
        "         max-height:200px; }\n"
        "</style>\n"
        "</head>\n"
        "<body>\n"
        f"<h2>ERD — {schema}</h2>\n"
        f"<p class=\"meta\">{n_tables} table(s) &nbsp;·&nbsp; {n_rels} relationship(s) &nbsp;·&nbsp;\n"
        "  Scroll to zoom &nbsp;·&nbsp; Drag to pan &nbsp;·&nbsp; Generated by Coruscant</p>\n"
        "<div class=\"toolbar\">\n"
        "  <button onclick=\"zoom(0.25)\">＋ Zoom in</button>\n"
        "  <button onclick=\"zoom(-0.25)\">－ Zoom out</button>\n"
        "  <button onclick=\"pz&&(pz.resetZoom(),pz.center())\">⊙ Reset</button>\n"
        "  <button onclick=\"pz&&pz.fit()\">⊞ Fit</button>\n"
        "</div>\n"
        "<div id=\"erd-wrap\">\n"
        "  <div class=\"mermaid\" style=\"width:100%;height:100%;\">\n"
        f"{mermaid}\n"
        "  </div>\n"
        "</div>\n"
        "<details>\n"
        "  <summary>▶ Mermaid source</summary>\n"
        f"  <pre>{mermaid}</pre>\n"
        "</details>\n"
        "<script>\n"
        "let pz = null;\n"
        "function zoom(delta) { if (!pz) return; pz.zoomBy(1 + delta); }\n"
        "mermaid.initialize({\n"
        "  startOnLoad: false, theme: 'dark',\n"
        "  er: { diagramPadding: 30, layoutDirection: 'TB', minEntityWidth: 100 }\n"
        "});\n"
        "async function init() {\n"
        "  try { await mermaid.run({ querySelector: '.mermaid' }); } catch(e) {}\n"
        "  const svg = document.querySelector('#erd-wrap svg');\n"
        "  if (!svg) return;\n"
        "  svg.removeAttribute('width'); svg.removeAttribute('height');\n"
        "  svg.style.width = '100%'; svg.style.height = '100%';\n"
        "  pz = svgPanZoom(svg, {\n"
        "    zoomEnabled: true, controlIconsEnabled: false,\n"
        "    fit: true, center: true, minZoom: 0.05, maxZoom: 50,\n"
        "    zoomScaleSensitivity: 0.3,\n"
        "  });\n"
        "  window.addEventListener('resize', () => { if (pz) { pz.resize(); pz.fit(); pz.center(); } });\n"
        "}\n"
        "document.addEventListener('DOMContentLoaded', init);\n"
        "</script>\n"
        "</body>\n"
        "</html>"
    )
